# Generated by Django 6.0.6 on 2026-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Semester 1"),
                    (2, "Semester 2"),
                    (3, "Semester 3"),
                    (4, "Semester 4"),
                    (5, "Semester 5"),
                    (6, "Semester 6"),
                    (7, "Semester 7"),
                    (8, "Semester 8"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
