# Generated by Django 6.0.6 on 2026-07-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_photo_student_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="enrollment_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
