from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.core.signing import TimestampSigner


signer = TimestampSigner()


def send_college_registration_email(college):
    """
    Send an email to the Super Admin whenever a new college registers.
    """

    token = signer.sign(str(college.id))

    base_url = "https://anantra.onrender.com"

    approve_url = (
        f"{base_url}/superadmin/action/approve/{college.id}/{token}/"
    )

    reject_url = (
        f"{base_url}/superadmin/action/reject/{college.id}/{token}/"
    )

    subject = f"New College Registration - {college.college_name}"

    text_content = f"""
A new college has registered on Anantra Campus.

College Name : {college.college_name}
College Code : {college.college_code}

Admin Email  : {college.admin.email}
College Email: {college.email}
Phone        : {college.phone}

Address      : {college.address}
City         : {college.city}
State        : {college.state}

Current Status : {college.status.title()}

Approve:
{approve_url}

Reject:
{reject_url}
"""

    html_content = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>

<body style="margin:0;padding:30px;background:#f4f6f9;font-family:Arial,sans-serif;">

<table align="center"
style="
max-width:700px;
width:100%;
background:#ffffff;
border-radius:10px;
padding:30px;
box-shadow:0 2px 10px rgba(0,0,0,.08);
">

<tr>
<td>

<h2 style="color:#0d6efd;">
🎓 New College Registration
</h2>

<p>
A new college has registered on
<strong>Anantra Campus</strong>.
</p>

<hr>

<table
style="width:100%;border-collapse:collapse;">

<tr>
<td><strong>College Name</strong></td>
<td>{college.college_name}</td>
</tr>

<tr>
<td><strong>College Code</strong></td>
<td>{college.college_code}</td>
</tr>

<tr>
<td><strong>Admin Email</strong></td>
<td>{college.admin.email}</td>
</tr>

<tr>
<td><strong>College Email</strong></td>
<td>{college.email}</td>
</tr>

<tr>
<td><strong>Phone</strong></td>
<td>{college.phone}</td>
</tr>

<tr>
<td><strong>Website</strong></td>
<td>{college.website or "-"}</td>
</tr>

<tr>
<td><strong>Address</strong></td>
<td>{college.address}</td>
</tr>

<tr>
<td><strong>City</strong></td>
<td>{college.city}</td>
</tr>

<tr>
<td><strong>State</strong></td>
<td>{college.state}</td>
</tr>

<tr>
<td><strong>Status</strong></td>
<td>
<span
style="
background:#ffc107;
padding:5px 12px;
border-radius:20px;
font-weight:bold;
">
{college.status.title()}
</span>
</td>
</tr>

</table>

<br><br>

<table align="center">
<tr>

<td>

<a href="{approve_url}"
style="
background:#198754;
color:white;
padding:14px 28px;
text-decoration:none;
border-radius:6px;
font-weight:bold;
display:inline-block;
">
✅ Approve
</a>

</td>

<td width="20"></td>

<td>

<a href="{reject_url}"
style="
background:#dc3545;
color:white;
padding:14px 28px;
text-decoration:none;
border-radius:6px;
font-weight:bold;
display:inline-block;
">
❌ Reject
</a>

</td>

</tr>
</table>

<br>

<p style="color:#666;">
This email was automatically generated by
<strong>Anantra Campus</strong>.
</p>

</td>
</tr>

</table>

</body>
</html>
"""

    email = EmailMultiAlternatives(
        subject=subject,
        body=text_content,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=["anantra.login7@gmail.com"],
    )

    email.attach_alternative(html_content, "text/html")

    email.send()